import type { Metadata } from 'next'
import { ClerkProvider, Show, SignInButton, SignUpButton, UserButton } from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { clerkModalAppearance } from '@/lib/clerk-modal-appearance'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Emaginary AI Studio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className='dark'>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ClerkProvider appearance={clerkModalAppearance}>
          <header>
            {/* <Show when="signed-out">
              <SignInButton mode='modal' />
              <SignUpButton mode='modal' />
            </Show>
            <Show when="signed-in">
              <UserButton />
            </Show> */}
          </header>
          {children}
        </ClerkProvider>
        <div className="fixed text-sm md:text-base p-2 backdrop-blur-md rounded right-2 border border-zinc-700/30 shadow bottom-1 text-center text-gray-500 z-50">
        <p>
          © Made with ❤️ by{" "}
          <a
            href="#"
            target="_blank"
            className="text-zinc-200 hover:underline"
            rel="noopener noreferrer"
          >
            Siddhartha 
          </a>{" "}🙇{" "}
        </p>
      </div>
      </body>
    </html>
  )
}